// Serbian language exercises — nouns and adjectives in various cases
// Each question: sentence with ___ blanks, placeholder base forms, correct answers
// To add more questions: append to the array and increment id (must be unique)

const QUESTIONS = [
  // === AKUZATIV — muški rod, živo (animate masculine, Acc = Gen) ===
  { id: 1,  padez: "akuzativ", broj: "jednina", sentence: "Vidim ___ ___ na ulici.",            placeholders: ["mlad",    "čovek"],     answers: ["mladog",      "čoveka"]      },
  { id: 2,  padez: "akuzativ", broj: "jednina", sentence: "Čekam ___ ___ na stanici.",          placeholders: ["dobar",   "drug"],      answers: ["dobrog",      "druga"]       },
  { id: 3,  padez: "akuzativ", broj: "jednina", sentence: "Zovem ___ ___ na telefon.",          placeholders: ["mali",    "brat"],      answers: ["malog",       "brata"]       },
  { id: 4,  padez: "akuzativ", broj: "jednina", sentence: "Volim ___ ___ veoma.",               placeholders: ["star",    "otac"],      answers: ["starog",      "oca"]         },
  { id: 5,  padez: "akuzativ", broj: "jednina", sentence: "Poznajem ___ ___ iz škole.",         placeholders: ["dobar",   "učitelj"],   answers: ["dobrog",      "učitelja"]    },
  { id: 6,  padez: "akuzativ", broj: "jednina", sentence: "Slušam ___ ___ svaki čas.",          placeholders: ["star",    "profesor"],  answers: ["starog",      "profesora"]   },
  { id: 7,  padez: "akuzativ", broj: "jednina", sentence: "Sreo sam ___ ___ na ulici.",         placeholders: ["poznat",  "glumac"],    answers: ["poznatog",    "glumca"]      },
  { id: 8,  padez: "akuzativ", broj: "jednina", sentence: "Pozdravljam ___ ___ svako jutro.",   placeholders: ["drag",    "komšija"],   answers: ["dragog",      "komšiju"]     },
  { id: 9,  padez: "akuzativ", broj: "jednina", sentence: "Posećujem ___ ___ svake nedelje.",   placeholders: ["bogat",   "ujak"],      answers: ["bogatog",     "ujaka"]       },
  { id: 10, padez: "akuzativ", broj: "jednina", sentence: "Gledam ___ ___ kako igra.",          placeholders: ["mlad",    "fudbaler"],  answers: ["mladog",      "fudbalera"]   },

  // === AKUZATIV — muški rod, neživo (inanimate masculine, Acc = Nom) ===
  { id: 11, padez: "akuzativ", broj: "jednina", sentence: "Čitam ___ ___ svake večeri.",        placeholders: ["dobri",     "roman"],     answers: ["dobri",       "roman"]       },
  { id: 12, padez: "akuzativ", broj: "jednina", sentence: "Kupujem ___ ___ u prodavnici.",      placeholders: ["novi",      "telefon"],   answers: ["novi",        "telefon"]     },
  { id: 13, padez: "akuzativ", broj: "jednina", sentence: "Gledam ___ ___ u bioskopu.",         placeholders: ["zanimljivi","film"],      answers: ["zanimljivi",  "film"]        },
  { id: 14, padez: "akuzativ", broj: "jednina", sentence: "Vozim ___ ___ svaki dan.",           placeholders: ["crveni",    "auto"],      answers: ["crveni",      "auto"]        },
  { id: 15, padez: "akuzativ", broj: "jednina", sentence: "Jedem ___ ___ za desert.",           placeholders: ["slatki",    "kolač"],     answers: ["slatki",      "kolač"]       },
  { id: 16, padez: "akuzativ", broj: "jednina", sentence: "Pišem ___ ___ za školu.",            placeholders: ["dugi",      "tekst"],     answers: ["dugi",        "tekst"]       },
  { id: 17, padez: "akuzativ", broj: "jednina", sentence: "Imam ___ ___ u centru.",             placeholders: ["veliki",    "stan"],      answers: ["veliki",      "stan"]        },
  { id: 18, padez: "akuzativ", broj: "jednina", sentence: "Tražim ___ ___ u ovoj firmi.",       placeholders: ["dobri",     "posao"],     answers: ["dobri",       "posao"]       },
  { id: 19, padez: "akuzativ", broj: "jednina", sentence: "Kupio sam ___ ___ juče.",            placeholders: ["lepi",      "kaput"],     answers: ["lepi",        "kaput"]       },
  { id: 20, padez: "akuzativ", broj: "jednina", sentence: "Pijem ___ ___ ujutru.",              placeholders: ["crni",      "čaj"],       answers: ["crni",        "čaj"]         },

  // === AKUZATIV — ženski rod ===
  { id: 21, padez: "akuzativ", broj: "jednina", sentence: "Vidim ___ ___ u parku.",             placeholders: ["mlada",       "devojka"],    answers: ["mladu",       "devojku"]     },
  { id: 22, padez: "akuzativ", broj: "jednina", sentence: "Volim ___ ___ tog pevača.",          placeholders: ["lepa",        "pesma"],      answers: ["lepu",        "pesmu"]       },
  { id: 23, padez: "akuzativ", broj: "jednina", sentence: "Čitam ___ ___ pred spavanje.",       placeholders: ["zanimljiva",  "priča"],      answers: ["zanimljivu",  "priču"]       },
  { id: 24, padez: "akuzativ", broj: "jednina", sentence: "Kupujem ___ ___ za proslavu.",       placeholders: ["nova",        "haljina"],    answers: ["novu",        "haljinu"]     },
  { id: 25, padez: "akuzativ", broj: "jednina", sentence: "Slušam ___ ___ u kolima.",           placeholders: ["tužna",       "muzika"],     answers: ["tužnu",       "muziku"]      },
  { id: 26, padez: "akuzativ", broj: "jednina", sentence: "Imam ___ ___ na polici.",            placeholders: ["dobra",       "knjiga"],     answers: ["dobru",       "knjigu"]      },
  { id: 27, padez: "akuzativ", broj: "jednina", sentence: "Gledam ___ ___ iz albuma.",          placeholders: ["stara",       "fotografija"],answers: ["staru",       "fotografiju"] },
  { id: 28, padez: "akuzativ", broj: "jednina", sentence: "Vidim ___ ___ na uglu.",             placeholders: ["visoka",      "zgrada"],     answers: ["visoku",      "zgradu"]      },
  { id: 29, padez: "akuzativ", broj: "jednina", sentence: "Kupujem ___ ___ na pijaci.",         placeholders: ["svež",        "jabuka"],     answers: ["svežu",       "jabuku"]      },
  { id: 30, padez: "akuzativ", broj: "jednina", sentence: "Gledam ___ ___ na televiziji.",      placeholders: ["nova",        "serija"],     answers: ["novu",        "seriju"]      },

  // === AKUZATIV — srednji rod (Acc = Nom) ===
  { id: 31, padez: "akuzativ", broj: "jednina", sentence: "Vidim ___ ___ u parku.",             placeholders: ["malo",   "dete"],      answers: ["malo",   "dete"]      },
  { id: 32, padez: "akuzativ", broj: "jednina", sentence: "Pijem ___ ___ posle posla.",         placeholders: ["hladno", "pivo"],      answers: ["hladno", "pivo"]      },
  { id: 33, padez: "akuzativ", broj: "jednina", sentence: "Čitam ___ ___ svaki dan.",           placeholders: ["kratko", "pismo"],     answers: ["kratko", "pismo"]     },
  { id: 34, padez: "akuzativ", broj: "jednina", sentence: "Kupujem ___ ___ za večeru.",         placeholders: ["belo",   "vino"],      answers: ["belo",   "vino"]      },
  { id: 35, padez: "akuzativ", broj: "jednina", sentence: "Volim ___ ___ i odmor.",             placeholders: ["toplo",  "leto"],      answers: ["toplo",  "leto"]      },

  // === GENITIV ===
  { id: 36, padez: "genitiv", broj: "jednina", sentence: "Bojim se ___ ___.",                          placeholders: ["velik",    "pas"],        answers: ["velikog",    "psa"]         },
  { id: 37, padez: "genitiv", broj: "jednina", sentence: "Nema ___ ___ kod kuće.",                     placeholders: ["star",     "čovek"],      answers: ["starog",     "čoveka"]      },
  { id: 38, padez: "genitiv", broj: "jednina", sentence: "Pijem čašu ___ ___.",                        placeholders: ["hladan",   "sok"],        answers: ["hladnog",    "soka"]        },
  { id: 39, padez: "genitiv", broj: "jednina", sentence: "Šetam oko ___ ___.",                         placeholders: ["malo",     "jezero"],     answers: ["malog",      "jezera"]      },
  { id: 40, padez: "genitiv", broj: "jednina", sentence: "Živim blizu ___ ___.",                       placeholders: ["velik",    "grad"],       answers: ["velikog",    "grada"]       },
  { id: 41, padez: "genitiv", broj: "jednina", sentence: "Idem kod ___ ___.",                          placeholders: ["dobar",    "prijatelj"],  answers: ["dobrog",     "prijatelja"]  },
  { id: 42, padez: "genitiv", broj: "jednina", sentence: "Ne mogu bez ___ ___.",                       placeholders: ["svež",     "kafa"],       answers: ["sveže",      "kafe"]        },
  { id: 43, padez: "genitiv", broj: "jednina", sentence: "Čekam ispred ___ ___.",                      placeholders: ["star",     "škola"],      answers: ["stare",      "škole"]       },
  { id: 44, padez: "genitiv", broj: "jednina", sentence: "Dolazim iz ___ ___.",                        placeholders: ["malo",     "selo"],       answers: ["malog",      "sela"]        },
  { id: 45, padez: "genitiv", broj: "jednina", sentence: "Ima puno ___ ___.",                          placeholders: ["slobodan", "vreme"],      answers: ["slobodnog",  "vremena"]     },
  { id: 46, padez: "genitiv", broj: "jednina", sentence: "Uzimam lek zbog ___ ___.",                   placeholders: ["jak",      "bol"],        answers: ["jakog",      "bola"]        },
  { id: 47, padez: "genitiv", broj: "jednina", sentence: "Vraćam se od ___ ___.",                      placeholders: ["dobar",    "lekar"],      answers: ["dobrog",     "lekara"]      },
  { id: 48, padez: "genitiv", broj: "jednina", sentence: "Uzeo sam parče ___ ___.",                    placeholders: ["ukusan",   "torta"],      answers: ["ukusne",     "torte"]       },
  { id: 49, padez: "genitiv", broj: "jednina", sentence: "Ispio je gutljaj ___ ___.",                  placeholders: ["topao",    "čaj"],        answers: ["toplog",     "čaja"]        },
  { id: 50, padez: "genitiv", broj: "jednina", sentence: "Vraćam se sa ___ ___.",                      placeholders: ["dug",      "put"],        answers: ["dugog",      "puta"]        },
  { id: 51, padez: "genitiv", broj: "jednina", sentence: "Plaši se ___ ___.",                          placeholders: ["visok",    "talas"],      answers: ["visokog",    "talasa"]      },
  { id: 52, padez: "genitiv", broj: "jednina", sentence: "Nema više ___ ___.",                         placeholders: ["dobar",    "lekar"],      answers: ["dobrog",     "lekara"]      },
  { id: 53, padez: "genitiv", broj: "jednina", sentence: "Čekam kraj ___ ___.",                        placeholders: ["dug",      "film"],       answers: ["dugog",      "filma"]       },
  { id: 54, padez: "genitiv", broj: "jednina", sentence: "Uzeo je komad ___ ___.",                     placeholders: ["svež",     "hleb"],       answers: ["svežeg",     "hleba"]       },
  { id: 55, padez: "genitiv", broj: "jednina", sentence: "Vratio se iz ___ ___.",                      placeholders: ["star",     "zemlja"],     answers: ["stare",      "zemlje"]      },

  // === DATIV ===
  { id: 56, padez: "dativ", broj: "jednina", sentence: "Dajem ___ ___ igračku.",             placeholders: ["mali",    "brat"],      answers: ["malom",    "bratu"]       },
  { id: 57, padez: "dativ", broj: "jednina", sentence: "Pišem ___ ___ pismo.",               placeholders: ["drag",    "prijatelj"], answers: ["dragom",   "prijatelju"]  },
  { id: 58, padez: "dativ", broj: "jednina", sentence: "Pomažem ___ ___ u kući.",            placeholders: ["star",    "baka"],      answers: ["staroj",   "baki"]        },
  { id: 59, padez: "dativ", broj: "jednina", sentence: "Govorim ___ ___ istinu.",            placeholders: ["malo",    "dete"],      answers: ["malom",    "detetu"]      },
  { id: 60, padez: "dativ", broj: "jednina", sentence: "Šaljem pismo ___ ___.",              placeholders: ["mlad",    "sestra"],    answers: ["mladoj",   "sestri"]      },
  { id: 61, padez: "dativ", broj: "jednina", sentence: "Zahvaljujem ___ ___ na pomoći.",     placeholders: ["dobar",   "doktor"],    answers: ["dobrom",   "doktoru"]     },
  { id: 62, padez: "dativ", broj: "jednina", sentence: "Verujem ___ ___ bezuslovno.",        placeholders: ["dobar",   "čovek"],     answers: ["dobrom",   "čoveku"]      },
  { id: 63, padez: "dativ", broj: "jednina", sentence: "Pridružujem se ___ ___.",            placeholders: ["veseo",   "grupa"],     answers: ["veseloj",  "grupi"]       },
  { id: 64, padez: "dativ", broj: "jednina", sentence: "Vraćam se ___ ___.",                 placeholders: ["rodni",   "kuća"],      answers: ["rodnoj",   "kući"]        },
  { id: 65, padez: "dativ", broj: "jednina", sentence: "Odgovaram ___ ___ na pitanje.",      placeholders: ["star",    "profesor"],  answers: ["starom",   "profesoru"]   },
  { id: 66, padez: "dativ", broj: "jednina", sentence: "Pošao je prema ___ ___.",            placeholders: ["nov",     "zgrada"],    answers: ["novoj",    "zgradi"]      },
  { id: 67, padez: "dativ", broj: "jednina", sentence: "Nosim poklon ___ ___.",              placeholders: ["mlada",   "devojka"],   answers: ["mladoj",   "devojci"]     },
  { id: 68, padez: "dativ", broj: "jednina", sentence: "Kažem ___ ___ da dođe.",            placeholders: ["dobar",   "drug"],      answers: ["dobrom",   "drugu"]       },

  // === INSTRUMENTAL ===
  { id: 69, padez: "instrumental", broj: "jednina", sentence: "Razgovaram sa ___ ___.",             placeholders: ["dobar",    "prijatelj"], answers: ["dobrim",    "prijateljem"] },
  { id: 70, padez: "instrumental", broj: "jednina", sentence: "Putuje sa ___ ___.",                 placeholders: ["mlad",     "sestra"],    answers: ["mladom",    "sestrom"]     },
  { id: 71, padez: "instrumental", broj: "jednina", sentence: "Pišem ___ ___.",                     placeholders: ["crven",    "olovka"],    answers: ["crvenom",   "olovkom"]     },
  { id: 72, padez: "instrumental", broj: "jednina", sentence: "Idem u školu sa ___ ___.",           placeholders: ["mali",     "brat"],      answers: ["malim",     "bratom"]      },
  { id: 73, padez: "instrumental", broj: "jednina", sentence: "Sreo sam se sa ___ ___.",            placeholders: ["star",     "kolega"],    answers: ["starim",    "kolegom"]     },
  { id: 74, padez: "instrumental", broj: "jednina", sentence: "Bavim se ___ ___.",                  placeholders: ["klasičan", "muzika"],    answers: ["klasičnom", "muzikom"]     },
  { id: 75, padez: "instrumental", broj: "jednina", sentence: "Vozim se ___ ___.",                  placeholders: ["brz",      "voz"],       answers: ["brzim",     "vozom"]       },
  { id: 76, padez: "instrumental", broj: "jednina", sentence: "Jede supu ___ ___.",                 placeholders: ["drvena",   "kašika"],    answers: ["drvenom",   "kašikom"]     },
  { id: 77, padez: "instrumental", broj: "jednina", sentence: "Bavio se ___ ___.",                  placeholders: ["jak",      "sport"],     answers: ["jakim",     "sportom"]     },
  { id: 78, padez: "instrumental", broj: "jednina", sentence: "Putovao je ___ ___.",                placeholders: ["star",     "brod"],      answers: ["starim",    "brodom"]      },
  { id: 79, padez: "instrumental", broj: "jednina", sentence: "Razgovara sa ___ ___.",              placeholders: ["pametna",  "devojka"],   answers: ["pametnom",  "devojkom"]    },
  { id: 80, padez: "instrumental", broj: "jednina", sentence: "Igra se sa ___ ___.",                placeholders: ["mali",     "pas"],       answers: ["malim",     "psom"]        },

  // === LOKATIV ===
  { id: 81, padez: "lokativ", broj: "jednina", sentence: "Živim u ___ ___.",                   placeholders: ["mali",      "grad"],      answers: ["malom",      "gradu"]       },
  { id: 82, padez: "lokativ", broj: "jednina", sentence: "Radim u ___ ___.",                   placeholders: ["velika",    "firma"],     answers: ["velikoj",    "firmi"]       },
  { id: 83, padez: "lokativ", broj: "jednina", sentence: "Sedim na ___ ___.",                  placeholders: ["tvrd",      "stolica"],   answers: ["tvrdoj",     "stolici"]     },
  { id: 84, padez: "lokativ", broj: "jednina", sentence: "Čitam o ___ ___.",                   placeholders: ["drevna",    "istorija"],  answers: ["drevnoj",    "istoriji"]    },
  { id: 85, padez: "lokativ", broj: "jednina", sentence: "Razmišljam o ___ ___.",              placeholders: ["dobar",     "posao"],     answers: ["dobrom",     "poslu"]       },
  { id: 86, padez: "lokativ", broj: "jednina", sentence: "Odsjeo sam u ___ ___.",              placeholders: ["lep",       "hotel"],     answers: ["lepom",      "hotelu"]      },
  { id: 87, padez: "lokativ", broj: "jednina", sentence: "Učim u ___ ___.",                    placeholders: ["nova",      "škola"],     answers: ["novoj",      "školi"]       },
  { id: 88, padez: "lokativ", broj: "jednina", sentence: "Stoji na ___ ___.",                  placeholders: ["hladan",    "pod"],       answers: ["hladnom",    "podu"]        },
  { id: 89, padez: "lokativ", broj: "jednina", sentence: "Pričamo o ___ ___.",                 placeholders: ["zanimljiv", "film"],      answers: ["zanimljivom","filmu"]        },
  { id: 90, padez: "lokativ", broj: "jednina", sentence: "Pronašao sam to na ___ ___.",        placeholders: ["stari",     "tavan"],     answers: ["starom",     "tavanu"]      },
  { id: 91, padez: "lokativ", broj: "jednina", sentence: "Bio sam na ___ ___.",                placeholders: ["dobar",     "koncert"],   answers: ["dobrom",     "koncertu"]    },
  { id: 92, padez: "lokativ", broj: "jednina", sentence: "Pisao je o ___ ___.",                placeholders: ["lep",       "priroda"],   answers: ["lepoj",      "prirodi"]     },
  { id: 93, padez: "lokativ", broj: "jednina", sentence: "Govori o ___ ___.",                  placeholders: ["star",      "vreme"],     answers: ["starom",     "vremenu"]     },
  { id: 94, padez: "lokativ", broj: "jednina", sentence: "Mislim o ___ ___.",                  placeholders: ["lepo",      "vreme"],     answers: ["lepom",      "vremenu"]     },

  // === MNOŽINA — nominativ ===
  { id: 95,  padez: "nominativ", broj: "množina", sentence: "___ ___ su stigli na vreme.",           placeholders: ["nov",       "student (mn.)"],      answers: ["novi",       "studenti"]      },
  { id: 96,  padez: "nominativ", broj: "množina", sentence: "___ ___ su bile lepe.",                 placeholders: ["star",      "pesma (mn.)"],        answers: ["stare",      "pesme"]         },
  { id: 97,  padez: "nominativ", broj: "množina", sentence: "___ ___ leže na stolu.",                placeholders: ["kratak",    "pismo (mn.)"],        answers: ["kratka",     "pisma"]         },
  { id: 98,  padez: "nominativ", broj: "množina", sentence: "___ ___ su skupi ove godine.",          placeholders: ["dobar",     "restoran (mn.)"],     answers: ["dobri",      "restorani"]     },
  { id: 99,  padez: "nominativ", broj: "množina", sentence: "___ ___ su pali u jesen.",              placeholders: ["žut",       "list (mn.)"],         answers: ["žuti",       "listovi"]       },
  { id: 100, padez: "nominativ", broj: "množina", sentence: "___ ___ su otvorene svaki dan.",        placeholders: ["mali",      "prodavnica (mn.)"],   answers: ["male",       "prodavnice"]    },
  { id: 101, padez: "nominativ", broj: "množina", sentence: "___ ___ su bila prazna zimi.",          placeholders: ["planinsko", "selo (mn.)"],         answers: ["planinska",  "sela"]          },
  { id: 102, padez: "nominativ", broj: "množina", sentence: "___ ___ su brzi i jaki.",               placeholders: ["mlad",      "igrač (mn.)"],        answers: ["mladi",      "igrači"]        },
  { id: 103, padez: "nominativ", broj: "množina", sentence: "___ ___ su bili tihi.",                 placeholders: ["star",      "pas (mn.)"],          answers: ["stari",      "psi"]           },
  { id: 104, padez: "nominativ", broj: "množina", sentence: "___ ___ su bile pune.",                 placeholders: ["veliki",    "učionica (mn.)"],     answers: ["velike",     "učionice"]      },

  // === MNOŽINA — akuzativ ===
  { id: 105, padez: "akuzativ", broj: "množina", sentence: "Vidim ___ ___ na prozoru.",             placeholders: ["beo",        "golub (mn.)"],        answers: ["bele",       "golubove"]      },
  { id: 106, padez: "akuzativ", broj: "množina", sentence: "Čitam ___ ___ svaki dan.",              placeholders: ["zanimljiv",  "članak (mn.)"],       answers: ["zanimljive", "članke"]        },
  { id: 107, padez: "akuzativ", broj: "množina", sentence: "Volim ___ ___.",                        placeholders: ["star",       "film (mn.)"],         answers: ["stare",      "filmove"]       },
  { id: 108, padez: "akuzativ", broj: "množina", sentence: "Kupujem ___ ___.",                      placeholders: ["crven",      "jabuka (mn.)"],       answers: ["crvene",     "jabuke"]        },
  { id: 109, padez: "akuzativ", broj: "množina", sentence: "Gledam ___ ___ na utakmici.",           placeholders: ["mlad",       "igrač (mn.)"],        answers: ["mlade",      "igrače"]        },
  { id: 110, padez: "akuzativ", broj: "množina", sentence: "Imam ___ ___ kod kuće.",                placeholders: ["dobra",      "knjiga (mn.)"],       answers: ["dobre",      "knjige"]        },
  { id: 111, padez: "akuzativ", broj: "množina", sentence: "Posetio sam ___ ___ u Evropi.",         placeholders: ["velik",      "grad (mn.)"],         answers: ["velike",     "gradove"]       },
  { id: 112, padez: "akuzativ", broj: "množina", sentence: "Volim ___ ___.",                        placeholders: ["tiho",       "jutro (mn.)"],        answers: ["tiha",       "jutra"]         },
  { id: 113, padez: "akuzativ", broj: "množina", sentence: "Jedemo ___ ___ svaki dan.",             placeholders: ["svež",       "salata (mn.)"],       answers: ["sveže",      "salate"]        },
  { id: 114, padez: "akuzativ", broj: "množina", sentence: "Gledam ___ ___ na stadionu.",           placeholders: ["dobar",      "utakmica (mn.)"],     answers: ["dobre",      "utakmice"]      },

  // === MNOŽINA — genitiv ===
  { id: 115, padez: "genitiv", broj: "množina", sentence: "Nema ___ ___ na tržištu.",              placeholders: ["dobar",  "posao (mn.)"],      answers: ["dobrih",  "poslova"]         },
  { id: 116, padez: "genitiv", broj: "množina", sentence: "Kupio je puno ___ ___.",                placeholders: ["nov",    "knjiga (mn.)"],     answers: ["novih",   "knjiga"]          },
  { id: 117, padez: "genitiv", broj: "množina", sentence: "Ima mnogo ___ ___ u gradu.",            placeholders: ["velik",  "zgrada (mn.)"],     answers: ["velikih", "zgrada"]          },
  { id: 118, padez: "genitiv", broj: "množina", sentence: "Nema ___ ___ u školi.",                 placeholders: ["dobar",  "učenik (mn.)"],     answers: ["dobrih",  "učenika"]         },
  { id: 119, padez: "genitiv", broj: "množina", sentence: "Vidim puno ___ ___ na nebu.",           placeholders: ["siv",    "oblak (mn.)"],      answers: ["sivih",   "oblaka"]          },
  { id: 120, padez: "genitiv", broj: "množina", sentence: "Imam dosta ___ ___ kod kuće.",          placeholders: ["star",   "stvar (mn.)"],      answers: ["starih",  "stvari"]          },
  { id: 121, padez: "genitiv", broj: "množina", sentence: "Nema ___ ___ u ovom gradu.",            placeholders: ["dobar",  "kafić (mn.)"],      answers: ["dobrih",  "kafića"]          },
  { id: 122, padez: "genitiv", broj: "množina", sentence: "Kupio je kilogram ___ ___.",            placeholders: ["svež",   "paradajz (mn.)"],   answers: ["svežih",  "paradajza"]       },
  { id: 123, padez: "genitiv", broj: "množina", sentence: "Nema više ___ ___ na lageru.",          placeholders: ["nov",    "model (mn.)"],      answers: ["novih",   "modela"]          },
  { id: 124, padez: "genitiv", broj: "množina", sentence: "Ima puno ___ ___ na sajmu.",            placeholders: ["velik",  "štand (mn.)"],      answers: ["velikih", "štandova"]        },

  // === MNOŽINA — dativ ===
  { id: 125, padez: "dativ", broj: "množina", sentence: "Pišem ___ ___.",                        placeholders: ["drag",   "roditelj (mn.)"],   answers: ["dragim",  "roditeljima"]     },
  { id: 126, padez: "dativ", broj: "množina", sentence: "Govorim ___ ___ istinu.",               placeholders: ["mlad",   "student (mn.)"],    answers: ["mladim",  "studentima"]      },
  { id: 127, padez: "dativ", broj: "množina", sentence: "Dajem ___ ___ nagradu.",                placeholders: ["dobar",  "učenik (mn.)"],     answers: ["dobrim",  "učenicima"]       },
  { id: 128, padez: "dativ", broj: "množina", sentence: "Zahvaljujem se ___ ___ na podršci.",    placeholders: ["dobar",  "prijatelj (mn.)"],  answers: ["dobrim",  "prijateljima"]    },
  { id: 129, padez: "dativ", broj: "množina", sentence: "Poklanjam knjige ___ ___.",             placeholders: ["mlad",   "kolega (mn.)"],     answers: ["mladim",  "kolegama"]        },
  { id: 130, padez: "dativ", broj: "množina", sentence: "Pomažem ___ ___ u učenju.",             placeholders: ["slab",   "učenik (mn.)"],     answers: ["slabim",  "učenicima"]       },
  { id: 131, padez: "dativ", broj: "množina", sentence: "Čestitam ___ ___ na pobedi.",           placeholders: ["dobar",  "pobednik (mn.)"],   answers: ["dobrim",  "pobednicima"]     },
  { id: 132, padez: "dativ", broj: "množina", sentence: "Šaljem mejl ___ ___.",                  placeholders: ["nov",    "zaposleni (mn.)"],  answers: ["novim",   "zaposlenima"]     },

  // === MNOŽINA — instrumental ===
  { id: 133, padez: "instrumental", broj: "množina", sentence: "Razgovaram sa ___ ___.",                placeholders: ["dobar",   "student (mn.)"],   answers: ["dobrim",    "studentima"]    },
  { id: 134, padez: "instrumental", broj: "množina", sentence: "Putovao je sa ___ ___.",                placeholders: ["mlad",    "prijatelj (mn.)"], answers: ["mladim",    "prijateljima"]  },
  { id: 135, padez: "instrumental", broj: "množina", sentence: "Upoznao sam se sa ___ ___.",            placeholders: ["nov",     "kolega (mn.)"],    answers: ["novim",     "kolegama"]      },
  { id: 136, padez: "instrumental", broj: "množina", sentence: "Igra se sa ___ ___.",                   placeholders: ["mali",    "drug (mn.)"],      answers: ["malim",     "drugovima"]     },
  { id: 137, padez: "instrumental", broj: "množina", sentence: "Bori se sa ___ ___.",                   placeholders: ["velik",   "problem (mn.)"],   answers: ["velikim",   "problemima"]    },
  { id: 138, padez: "instrumental", broj: "množina", sentence: "Deli sobu sa ___ ___.",                 placeholders: ["dobar",   "cimer (mn.)"],     answers: ["dobrim",    "cimerima"]      },
  { id: 139, padez: "instrumental", broj: "množina", sentence: "Bavi se ___ ___.",                      placeholders: ["različit","sport (mn.)"],     answers: ["različitim","sportovima"]    },
  { id: 140, padez: "instrumental", broj: "množina", sentence: "Radi sa ___ ___.",                      placeholders: ["mlad",    "lekar (mn.)"],     answers: ["mladim",    "lekarima"]      },

  // === MNOŽINA — lokativ ===
  { id: 141, padez: "lokativ", broj: "množina", sentence: "Pričam o ___ ___.",                     placeholders: ["star",    "film (mn.)"],      answers: ["starim",    "filmovima"]     },
  { id: 142, padez: "lokativ", broj: "množina", sentence: "Učimo o ___ ___.",                      placeholders: ["stara",   "civilizacija (mn.)"], answers: ["starim", "civilizacijama"] },
  { id: 143, padez: "lokativ", broj: "množina", sentence: "Bio sam na ___ ___.",                   placeholders: ["razni",   "put (mn.)"],       answers: ["raznim",    "putevima"]      },
  { id: 144, padez: "lokativ", broj: "množina", sentence: "Mislim o ___ ___.",                     placeholders: ["dobar",   "vreme (mn.)"],     answers: ["dobrim",    "vremenima"]     },
  { id: 145, padez: "lokativ", broj: "množina", sentence: "Govorimo o ___ ___.",                   placeholders: ["mlad",    "glumac (mn.)"],    answers: ["mladim",    "glumcima"]      },
  { id: 146, padez: "lokativ", broj: "množina", sentence: "Pričamo o ___ ___.",                    placeholders: ["star",    "dan (mn.)"],       answers: ["starim",    "danima"]        },
  { id: 147, padez: "lokativ", broj: "množina", sentence: "Radio je u ___ ___.",                   placeholders: ["velik",   "grad (mn.)"],      answers: ["velikim",   "gradovima"]     },
  { id: 148, padez: "lokativ", broj: "množina", sentence: "Govori o ___ ___.",                     placeholders: ["stran",   "zemlja (mn.)"],    answers: ["stranim",   "zemljama"]      },
  { id: 149, padez: "lokativ", broj: "množina", sentence: "Mislim o ___ ___.",                     placeholders: ["star",    "prijatelj (mn.)"], answers: ["starim",    "prijateljima"]  },
  { id: 150, padez: "lokativ", broj: "množina", sentence: "Pričamo o ___ ___.",                    placeholders: ["nov",     "projekt (mn.)"],   answers: ["novim",     "projektima"]    },
];
